name: Deploy to swag-stitch.dhimansoft.com

on:
  push:
    branches:
      - main   # or whichever branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install and build frontend
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build project
        working-directory: ./Frontend
        run: npm run build

      # Deploy via FTP
      - name: Upload via FTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 22 # or 21 for FTP
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp # or ftp depending on your host
          server-dir: /swag-stitch.dhimansoft.com/
          local-dir: ./Frontend/dist/